github:
  is_project_page: false

theme: jekyll-theme-Cayman
markdown: GFM
title: Workshop on Embodied and Cognitive Health AI Technologies
description: 25th International Conference on Next Generation Wired/Wireless Networks and Systems
